name: Update Weekly Menu

on:
  schedule:
    - cron: '0 14 * * 0'   # 매주 일요일 오후 11시 (UTC 기준 14시)
  workflow_dispatch:   # 수동 실행

jobs:
  update-menu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          pip install requests beautifulsoup4 pdf2image PyGithub

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_script.py
          
